language: php
php:
- '8.0'
branches:
  only:
  - master
  - 1.0
env:
- LARAVEL_VERSION=^8.0
matrix:
  fast_finish: true
before_install:
- composer require "laravel/framework:${LARAVEL_VERSION}"
install:
- composer update --prefer-source --no-interaction --dev
after_success:
- travis_retry php vendor/bin/coveralls